export const GET_FEEDS_SUCCESS = "GET_FEEDS_SUCCESS";
export const GET_FEEDS_FAILURE = "GET_FEEDS_FAILURE";
export const NETWORK_CONNECTION_ERROR = "NETWORK_CONNECTION_ERROR";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const BLOCK_FOLLOWING_SUCCESS = "BLOCK_FOLLOWING_SUCCESS";
export const BLOCK_FOLLOWING_FAILURE = "BLOCK_FOLLOWING_FAILURE";

export const MUTE_FOLLOWING_SUCCESS = "MUTE_FOLLOWING_SUCCESS";
export const MUTE_FOLLOWING_FAILURE = "MUTE_FOLLOWING_FAILURE";

export const LIKE_TWEET_SUCCESS = "LIKE_TWEET_SUCCESS";
export const LIKE_TWEET_FAILURE = "LIKE_TWEET_FAILURE";

export const UNLIKE_TWEET_SUCCESS = "UNLIKE_TWEET_SUCCESS";
export const UNLIKE_TWEET_FAILURE = "UNLIKE_TWEET_FAILURE";

export const RETWEET_SUCCESS = "RETWEET_SUCCESS";
export const RETWEET_FAILURE = "RETWEET_FAILURE";

export const REPLYTO_TWEET_SUCCESS = "REPLYTO_TWEET_SUCCESS";
export const REPLYTO_TWEET_FAILURE = "REPLYTO_TWEET_FAILURE";

export const TWEET_SUCCESS = "TWEET_SUCCESS";
export const TWEET_FAILURE = "TWEET_FAILURE";

export const UNFOLLOW_SUCCESS = "UNFOLLOW_SUCCESS";
export const UNFOLLOW_FAILURE = "UNFOLLOW_FAILURE";

export const GET_BOOKMARKS_SUCCESS = "GET_BOOKMARKS_SUCCESS";
export const GET_BOOKMARKS_FAILURE = "GET_BOOKMARKS_FAILURE";

export const BOOKMARK_TWEET_FAILURE = "BOOKMARK_TWEET_FAILURE";
export const BOOKMARK_TWEET_SUCCESS = "BOOKMARK_TWEET_SUCCESS";

export const UNBOOKMARK_TWEET_FAILURE = "UNBOOKMARK_TWEET_FAILURE";
export const UNBOOKMARK_TWEET_SUCCESS = "UNBOOKMARK_TWEET_SUCCESS";

export const GET_LIST_SUCCESS = "GET_LIST_SUCCESS";
export const GET_LIST_FAILURE = "GET_LIST_FAILURE";

export const GET_USER_LIST = "GET_USER_LIST";

export const SEARCH_USER="SEARCH_USER";
export const SEARCH_HASHTAG="SEARCH_HASHTAG";
export const VIEW_LIST="VIEW_LIST";

export const CLEAR_FEEDS = "CLEAR_FEEDS";
export const CLEAR_CHECKS = "CLEAR_CHECKS";

export const SIGNUP ='SIGNUP';
export const LOGIN ='LOGIN';
export const GET_PROFILE ='GET_PROFILE';
export const UPDATE_PROFILE ='UPDATE_PROFILE';
export const NEW_MESSAGE='NEW_MESSAGE';
export const INBOX_MESSAGES='INBOX_MESSAGES';
export const IMAGE_DOWNLOAD='IMAGE_DOWNLOAD';
export const IMAGE_UPLOAD='IMAGE_UPLOAD';
export const DELETEUSER='DELETEUSER';

export const FOLLOWER_NO='FOLLOWER_NO';
export const FOLLOWING_NO='FOLLOWING_NO';

export const IS_FOLLOWING='IS_FOLLOWING';
export const FOLLOW='FOLLOW';
export const UNFOLLOW='UNFOLLOW';

export const FOLLOWERSDATA='FOLLOWERSDATA';
export const FOLLOWINGDATA='FOLLOWINGDATA';

export const GET_USER_TWEET_SUCCESS = "GET_USER_TWEET_SUCCESS";
export const GET_USER_TWEET_FAILURE = "GET_USER_TWEET_FAILURE";
