export const GET_FEEDS_SUCCESS = "GET_FEEDS_SUCCESS";
export const GET_FEEDS_FAILURE = "GET_FEEDS_FAILURE";
export const NETWORK_CONNECTION_ERROR = "NETWORK_CONNECTION_ERROR";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const BLOCK_FOLLOWING_SUCCESS = "BLOCK_FOLLOWING_SUCCESS";
export const BLOCK_FOLLOWING_FAILURE = "BLOCK_FOLLOWING_FAILURE";

export const MUTE_FOLLOWING_SUCCESS = "MUTE_FOLLOWING_SUCCESS";
export const MUTE_FOLLOWING_FAILURE = "MUTE_FOLLOWING_FAILURE";

export const LIKE_TWEET_SUCCESS = "LIKE_TWEET_SUCCESS";
export const LIKE_TWEET_FAILURE = "LIKE_TWEET_FAILURE";

export const UNLIKE_TWEET_SUCCESS = "UNLIKE_TWEET_SUCCESS";
export const UNLIKE_TWEET_FAILURE = "UNLIKE_TWEET_FAILURE";

export const RETWEET_SUCCESS = "RETWEET_SUCCESS";
export const RETWEET_FAILURE = "RETWEET_FAILURE";

export const REPLYTO_TWEET_SUCCESS = "REPLYTO_TWEET_SUCCESS";
export const REPLYTO_TWEET_FAILURE = "REPLYTO_TWEET_FAILURE";

export const TWEET_SUCCESS = "TWEET_SUCCESS";
export const TWEET_FAILURE = "TWEET_FAILURE";

export const GET_BOOKMARKS_SUCCESS = "GET_BOOKMARKS_SUCCESS";
export const GET_BOOKMARKS_FAILURE = "GET_BOOKMARKS_FAILURE";

export const CLEAR_FEEDS = "CLEAR_FEEDS";

